### ISSUE TITLE
report android bugs

### ISSUE THREAD

**Issue by falkorichter** [falkorichter/android-simple-bike-computer#1]
Here is one nullpointer in the stack:

unregisterApp() - mClientIf=6
08-13 09:12:16.316    8905-8916/de.falkorichter.android.simplebikecomputer D/BluetoothGatt﹕ onClientConnectionState() - status=0 clientIf=6 device=C8:97:6F:D9:41:DE
08-13 09:12:16.326    8905-8916/de.falkorichter.android.simplebikecomputer W/BluetoothGatt﹕ Unhandled exception in callback
    java.lang.NullPointerException
            at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:168)
            at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:71)
            at android.os.Binder.execTransact(Binder.java:404)
            at dalvik.system.NativeStart.run(Native Method)

**Comment by BytesZero** [comment]
@falkorichter 
It seems you can't call these method together. The disconnection callback might arrive later than close() method performed.

You can add  mGatt.close(); into onConnectionStateChange callback to close the connection.
